import Footer from '@/components/layout/footer'
import Header from '@/components/layout/header'
import { elmsSans } from '@/lib/font'
import type { Metadata } from "next"
import "./globals.css"

export const metadata: Metadata = {
  title: "Savam Cleaning",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${elmsSans.className} antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
